Repository 8p/EightPointsGuzzleBundle, pull requests merged in 2018-10, with the labels that each got.

#215 Add option to create lazy clients
  README.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/EightPointsGuzzleExtension.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: enhancement, hacktoberfest

#216 [Profiler] Add request profiling to performance metrics
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/EightPointsGuzzleExtension.php
  src/Middleware/ProfileMiddleware.php
  src/Resources/config/services.xml
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
  tests/Middleware/ProfileMiddlewareTest.php
Labels: enhancement, hacktoberfest

#221 Add the option to use a custom handler class such as Guzzle MockHandler
  README.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/EightPointsGuzzleExtension.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
Labels: enhancement, hacktoberfest

#228 Show profiler in yellow when a response is slow
  README.md
  src/DataCollector/HttpDataCollector.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/EightPointsGuzzleExtension.php
  src/Resources/views/debug.html.twig
  tests/DataCollector/HttpDataCollectorTest.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: enhancement

#217 Add Configuration Reference
  README.md
  src/Resources/doc/configuration-reference.md
Labels: documentation, hacktoberfest

#236 Non public profiler creates error in SF 2.8
  src/DependencyInjection/EightPointsGuzzleExtension.php
Labels: bug

#237 Covered with tests issue 229
  tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
Labels: enhancement
