Repository 8p/EightPointsGuzzleBundle, pull requests merged in 2019-10, with the labels that each got.

#270 Move logging middlewares before plugins initialization
  src/DependencyInjection/EightPointsGuzzleExtension.php
  src/Middleware/ProfileMiddleware.php
  src/Middleware/RequestTimeMiddleware.php
Labels: bug

#267 Print Curl command for debugging purposes
  composer.json
  src/Log/LogMessage.php
  src/Log/Logger.php
  src/Resources/views/profiler.html.twig
  tests/Log/LoggerTest.php
Labels: enhancement

#271 [Profiler] Change color in left menu based on http status code
  src/Resources/views/debug.html.twig
Labels: enhancement

#272 Rename EightPointsGuzzleBundlePlugin to follow PSR
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/EightPointsGuzzleExtension.php
  src/EightPointsGuzzleBundle.php
  src/PluginInterface.php
  src/Resources/doc/how-to-create-a-single-file-plugin.md
  tests/DependencyInjection/EightPointsGuzzleExtensionTest.php
  tests/EightPointsGuzzleBundleTest.php
Labels: enhancement

#273 Remove Symfony Insights badge and config
  .gitattributes
  .sensiolabs.yml
  README.md
Labels: ready for review

#278 Add total time to profiler.
  src/Resources/public/css/main.css
  src/Resources/views/profiler.html.twig
Labels: enhancement
